apiVersion: v1
kind: Service
metadata:
  name: deployer-service
  namespace: deployer-system

spec:
  type: ClusterIP

  ports:
  - name: deployer
    port: 3000
    targetPort: deployer
  - name: deployer-debug
    port: 4000
    targetPort: deployer-debug
  # - name: metrics
  #   port: 4000
  #   targetPort: metrics
  # - name: metrics-debug
  #   port: 4010
  #   targetPort: metrics-debug
  # - name: prometheus
  #   port: 4020
  #   targetPort: metrics-prom
