apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
  namespace: deployer-system

spec:
  selector:
    matchLabels:
      app: deployer

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: deployer
    
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: deployer
        resources:
          requests:
            cpu: "250m"     # I need access to 25ms/100ms on one core
            memory: "36Mi"  # Use this same value for limits
          limits:
            cpu: "250m"     # Execute instructions 25ms/100ms on one core
            memory: "36Mi"  # Match the requests value