apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployer/

patches:
  - path: ./dev-deployer-patch-deploy.yaml
images:
  - name: service-image
    newName: service/deployer
    newTag: 0.0.1