apiVersion: v1
kind: Namespace
metadata:
  name: deployer-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
  namespace: deployer-system

spec:
  selector:
    matchLabels:
      app: deployer

  template:
    metadata:
      labels:
        app: deployer

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: deployer
        image: service-image
        resources:
          limits:
            memory: "36Mi"  
            cpu: "500m"  
          requests:
            memory: "36Mi"  
            cpu: "500m"  

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu