apiVersion: v1
kind: Namespace
metadata:
  name: deployer-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
  namespace: deployer-system

spec:
  selector:
    matchLabels:
      app: deployer

  template:
    metadata:
      labels:
        app: deployer

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: deployer
        image: Service-image
        resources:
          limits:
            memory: "36Mi"  
            cpu: "250m"  
          requests:
            memory: "36Mi"  
            cpu: "250m"  
        
---

apiVersion: v1
kind: Service
metadata:
  name: deployer-service
  namespace: deployer-system

spec:
  selector:
    app: deployer
